# Generated by Django 4.1.7 on 2023-03-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='https://loremflickr.com/861/559/food,cook', upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
